pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                sh 'git clone https://github.com/PhucPham96/docker-spring-boot-mysql-demo.git'
            }
        }
    }
}